apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "edu"
  POSTGRES_PASSWORD: "0000"
  POSTGRES_DB: "usuarios"
