apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
  replicas: 3 # Tells deployment to run X pods matching the template
  template: # Create pods using pod definition in this template
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: app:latest
          imagePullPolicy: IfNotPresent # Usar la imagen local si está disponible y solo intentar descargarla de un registry si no lo está
          envFrom:
            - configMapRef:
                name: postgres-config
            - configMapRef:
                name: redis-config
          ports:
            - containerPort: 80
