apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-static-pv
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/app-static
