apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - port: 80 # puerto en el que el servicio está escuchando dentro del cluster
      targetPort: 5000 # puerto en el que el servicio redirige el tráfico al pod
      protocol: TCP
  selector:
    app: app
