apiVersion: v1
kind: Service
metadata:
  name: app-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
    - port: 80 # puerto en el que el servicio está escuchando dentro del cluster
      targetPort: 5000 # puerto en el que el servicio redirige el tráfico al pod
      protocol: TCP
      # nodePort: 30008
  selector:
    app: app
